language: cpp

compiler:
    - gcc
    - clang
env:
    - BUILD_TYPE=Debug   STD=c++0x
    - BUILD_TYPE=Release STD=c++0x
    - BUILD_TYPE=Debug   STD=c++11
    - BUILD_TYPE=Release STD=c++11

matrix:
    exclude:
        - compiler: clang
          env: STD=c++0x

before_script:
    - source .travis-setup.sh
    - mkdir build && cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-std=${STD}"
    - make
    - make CTEST_OUTPUT_ON_FAILURE=1 test
