language: cpp
matrix:
    include:
        - compiler: gcc
          env: BUILD_TYPE=Debug STD=c++0x
        - compiler: gcc
          env: BUILD_TYPE=Release STD=c++0x
        - compiler: gcc
          env: BUILD_TYPE=Debug STD=c++11
        - compiler: gcc
          env: BUILD_TYPE=Release STD=c++11
        - compiler: clang
          env: BUILD_TYPE=Debug STD=c++11
        - compiler: clang
          env: BUILD_TYPE=Release STD=c++11

before_script:
    - source .travis-setup.sh
    - mkdir build && cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-std=${STD}"
    - make
    - make CTEST_OUTPUT_ON_FAILURE=1 test
