
language:
    - cpp
os:
    - linux
env:
    - BUILD_TYPE=Debug   STD=c++0x
    - BUILD_TYPE=Release STD=c++0x
    - BUILD_TYPE=Debug   STD=c++11
    - BUILD_TYPE=Release STD=c++11

before_install:
    - if [ "$STD" = "c++11" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - if [ "$STD" = "c++11" ]; then sudo apt-get update -qq; fi

install:
    - if [ "$STD" = "c++11" ]; then sudo apt-get install -qq gcc-4.8 g++-4.8; fi
    - if [ "$STD" = "c++11" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
    - mkdir depends && cd depends
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
    - sudo sh cmake-3.2.1-Linux-x86_64.sh --prefix=/opt/cmake
    - cd .. && sudo rm -rf depends
    - export PATH=/opt/cmake/bin:$PATH
    - cmake --version

before_script:
    - mkdir build && cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-std=${STD}"
    - make
    - make CTEST_OUTPUT_ON_FAILURE=1 test
