name: clang-format-lint
on:
  push: {}
  pull_request: {}

env:
  CMAKE_GENERATOR: Ninja

permissions:
  contents: read

jobs:
  job:
    name: check-clang-format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: DoozyX/clang-format-lint-action@bcb4eb2cb0d707ee4f3e5cc3b456eb075f12cf73 # v0.20
      with:
        source: './include/benchmark ./src ./test ./bindings'
        clangFormatVersion: 18
