name: cpp-linter

on:
  push: {}
  pull_request: {}

jobs:
  job:
    name: run-clang-tidy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: cpp-linter/cpp-linter-action@v2
      id: linter
      with:
        style: 'file'
        tidy-checks: ''
        extensions: 'c,h,cc'
    - name: fail fast format
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1
    - name: fail fast tidy
      if: steps.linter.outputs.clang-tidy-checks-failed > 0
      run: exit 1
