name: OSSF Scorecard Weekly

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ossf-scorecard:
    # To write a badge
    permissions:
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@2d1146689b8cda280b9bc96326124645441f03bc # v2.4.4
        with:
          publish_results: true
          results_file: ossf_scorecard.json
          results_format: json
